id: opecha:P000287
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG25918
  title: དཔལ་ལྡན་ས་སྐྱའི་གདུང་རབས་ལོ་རྒྱུས་ལས་གསར་བུ་བ་རྣམས་ཀྱི་ལྟ་བའི་མེ་ལོང་།
  volume:
    f10bbf7c23664764866e106bfa2d1f6a:
      image_group_id: I1KG26062
      title: Volume 1 of dpal ldan sa skya'i gdung rabs lo rgyus las gsar bu ba rnams
        kyi lta ba'i me long_/
      volume_number: 1
      total_pages: 118
  author: ''
ebook_metadata:
  title: དཔལ་ལྡན་ས་སྐྱའི་གདུང་རབས་ལོ་རྒྱུས་ལས་གསར་བུ་བ་རྣམས་ཀྱི་ལྟ་བའི་མེ་ལོང་།
  author: ''
  sku: P000287
  cover: cover.jpg
  layers:
  - pagination
