id: P000287
initial_creation_type: ocr
created_at: 21/02/2020
last_modified_at: 2021-12-16 15:32:07.707095
source_metadata:
  id: bdr:W1KG25918
  title: དཔལ་ལྡན་ས་སྐྱའི་གདུང་རབས་ལོ་རྒྱུས་ལས་གསར་བུ་བ་རྣམས་ཀྱི་ལྟ་བའི་མེ་ལོང་།
  author: ''
  volumes:
    f10bbf7c23664764866e106bfa2d1f6a:
      image_group_id: I1KG26062
      title: Volume 1 of dpal ldan sa skya'i gdung rabs lo rgyus las gsar bu ba rnams
        kyi lta ba'i me long_/
      volume_number: 1
      total_pages: 118
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
